# Generated by Django 2.2 on 2019-04-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
