# Generated by Django 2.2 on 2019-04-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='num',
        ),
    ]
