# Generated by Django 2.2 on 2019-04-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_delete_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='grupo',
        ),
    ]
