# Generated by Django 2.2 on 2019-04-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20190429_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='num',
            new_name='nume',
        ),
    ]
