# Generated by Django 2.2 on 2019-04-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190429_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='nume',
            new_name='numero',
        ),
    ]
