# Generated by Django 2.2 on 2019-04-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190428_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name_plural': 'Produtes'},
        ),
    ]
