# Generated by Django 2.2 on 2019-04-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20190428_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produt',
        ),
        migrations.AlterModelOptions(
            name='produt',
            options={'verbose_name_plural': 'Produtos'},
        ),
    ]
