# Generated by Django 2.2 on 2019-04-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20190429_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='numer',
            new_name='telefone',
        ),
    ]
