# Generated by Django 2.2 on 2019-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20190429_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=True, to='cliente.Cliente'),
            preserve_default=False,
        ),
    ]
