# Generated by Django 2.2 on 2019-04-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_auto_20190429_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpf',
            old_name='numero',
            new_name='numer',
        ),
    ]
