# Generated by Django 2.2 on 2019-04-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_auto_20190429_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpf',
            old_name='numer',
            new_name='Numero',
        ),
    ]
