# Generated by Django 2.2 on 2019-04-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_auto_20190429_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dt_criacao',
        ),
    ]
